FROM centos:7
MAINTAINER Geoff Williams <geoff.williams@puppetlabs.com>
ENV container docker
ENV pe_version <%= @pe_version %>

# puppet needs full systemd
RUN yum -y swap -- remove systemd-container systemd-container-libs -- install systemd systemd-libs \
  yum -y update; yum clean all; \
  (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
  rm -f /lib/systemd/system/multi-user.target.wants/*;\
  rm -f /etc/systemd/system/*.wants/*;\
  rm -f /lib/systemd/system/local-fs.target.wants/*; \
  rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
  rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
  rm -f /lib/systemd/system/basic.target.wants/*;\
  rm -f /lib/systemd/system/anaconda.target.wants/*;
  VOLUME [ "/sys/fs/cgroup" ]

# turn off annoying yum pauses
RUN echo "metadata_expire=never" >> /etc/yum.conf

# essential packages
RUN yum install -y sudo curl ntpdate which git cronie wget policycoreutils policycoreutils-restorecond iptables-services iptables
RUN yum groupinstall -y 'Development Tools'

# firewall off
# We can't stop systemctl services until after we come back up in priviledged
# mode.  Since this is a reboot and we just turned it off, firewalld will now
# be off we dont need to worry about it
# RUN systemctl stop firewalld
# RUN systemctl disable firewalld

# PE2015.3.0 seems to not be able to find openssl in its own path for 
# some reason - symlink to /usr/bin and then it should be live when it
# needs it
RUN ln -s /opt/puppetlabs/puppet/bin/openssl /usr/bin/openssl
RUN ln -s /opt/puppetlabs/server/bin/keytool /usr/bin/keytool


# copy and unpack PE - ADD command unpacks tarballs for us, how mad is that!
ADD ./puppet-enterprise-${pe_version}-el-7-x86_64.tar.gz /root

# fix locale, paths and terminal globally
RUN echo 'export LC_ALL="en_US.UTF-8"' >> /etc/profile.d/zz_docker_puppet.sh && \
  echo 'export PATH=/opt/puppetlabs/puppet/bin/:${PATH}' >> /etc/profile.d/zz_docker_puppet.sh && \
  echo 'export TERM=xterm' >> /etc/profile.d/zz_docker_puppet.sh

# puppet
EXPOSE 8140

# puppet pxp/pcp
EXPOSE 8142

# puppet enterprise web console
EXPOSE 443

# mcollective agent
EXPOSE 61613

# mcollective hub/spoke
EXPOSE 61616

# dockerbuild REST interface
EXPOSE 9000

# stop DiD from eating all disk if we choose to use it
VOLUME [ "/var/lib/docker" ]

CMD ["/usr/sbin/init"]

# !!!CANNOT!!! RUN THE INSTALLER UNTIL WE HAVE RELOADED IN PRIVILEGED MODE
#&& ./puppet-enterprise-installer -a answers/all-in-one.answers.txt
